### ISSUE TITLE
Cannot access 'watcher' before initialization.  error

### ISSUE THREAD

**Issue by ali-farooq0** [Redocly/openapi-cli#163]
Trying the latest beta version `1.0.0-beta.2` to preview docs is not working :sadface:

```
~> npx @redocly/openapi-cli --version
1.0.0-beta.2
~> npx @redocly/openapi-cli preview-docs server/api/api.yaml
Using Redoc community edition.
Login with openapi-cli login or use an enterprise license key to preview with the premium docs.


  🔎  Preview server running at http://127.0.0.1:8080
(node:54683) UnhandledPromiseRejectionWarning: TypeError: Non-string provided as watch path: server/api/api.yaml,
    at unifyPaths (/Users/alifarooq/.npm/_npx/54683/lib/node_modules/@redocly/openapi-cli/node_modules/chokidar/index.js:94:11)
    at FSWatcher.add (/Users/alifarooq/.npm/_npx/54683/lib/node_modules/@redocly/openapi-cli/node_modules/chokidar/index.js:395:15)
    at Object.watch (/Users/alifarooq/.npm/_npx/54683/lib/node_modules/@redocly/openapi-cli/node_modules/chokidar/index.js:936:11)
    at Object.<anonymous> (/Users/alifarooq/.npm/_npx/54683/lib/node_modules/@redocly/openapi-cli/lib/cli/preview-docs.js:72:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/alifarooq/.npm/_npx/54683/lib/node_modules/@redocly/openapi-cli/lib/cli/preview-docs.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:54683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:54683) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Bundling...

Something went wrong when processing server/api/api.yaml:

  - Cannot access 'watcher' before initialization.
```

Version `0.12.16` work fine without any issues.
```
npx @redocly/openapi-cli@0.12.16 preview-docs server/api/api.yaml
```

**Comment by ali-farooq0** [comment]
Looks like https://github.com/Redocly/openapi-cli/pull/164 may have fixed this issue. Thanks @knidarkness!

```
npx @redocly/openapi-cli@1.0.0-beta.3 preview-docs server/api/api.yaml
Using Redoc community edition.
Login with openapi-cli login or use an enterprise license key to preview with the premium docs.


  🔎  Preview server running at http://127.0.0.1:8080

Bundling...


  👀  Watching server/api/api.yaml and all related resources for changes

Created a bundle for server/api/api.yaml successfully
```

Closing as fixed.
