### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by diogui** [Redocly/openapi-cli#198]
**Describe the bug**
After Running openapi -h I get an error,

**To Reproduce**
1.npm install -g @redocly/openapi-cli
2.openapi -h

**Expected behavior**
openapi-cli options

**Logs**
`openapi -h
/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/simple-websocket/server.js:45
  _handleListening = () => {
                   ^

SyntaxError: Unexpected token =
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
`

**OpenAPI definition**
If applicable, add an OpenAPI definition and `.redocly.yaml` configuration file that helps reproduce the problem.

**Version(s)**
v1.0.0-beta.12

**Comment by knidarkness** [comment]
Could you also tell, which version of Node.js are you using?

**Comment by adamaltman** [comment]
If we don't support specific node.js versions, can we please restrict them in `package.json` using [engines](https://docs.npmjs.com/files/package.json#engines)?

**Comment by knidarkness** [comment]
@diogui , thanks for opening an issue. Based on the error it seems that you are using Node.js with version `<= 10`. Unfortunately, `openapi-cli` supports Node.js versions `>= 12`.

If that's not the case, please let us know.

As for the unsupported Node.js versions, I've added restrictions to the `package.json` in #201

**Comment by diogui** [comment]
Thanks for the quick reply. Indeed I'm using v10.15.0 . I'm sorry i didn't know that you only support node.js versions >= 12. I've updated node for the latest version (12.18.3) and now it's working. Thanks guys !
