### ISSUE TITLE
Showing stacktrace by default for incorrect login 

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#258]
**Describe the bug**
I see a stacktrace in the output.
```
➜  ~ openapi login

  🔑 Copy your API key from https://app.redoc.ly/profile and paste it below:


  Logging in...
GqlRequestError: Query failed: permission denied for table definition
    at Object.<anonymous> (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/redocly/query.js:33:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/redocly/query.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Authorization failed. Please check if you entered a valid token.
```

**To Reproduce**
1. `openapi login`
2. Put an invalid API key (e.g. aaabbb).
3. See error

**Expected behavior**
I didn't expect to see this part:

```
GqlRequestError: Query failed: permission denied for table definition
    at Object.<anonymous> (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/redocly/query.js:33:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/redocly/query.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I expected:

```
➜  ~ openapi login

  🔑 Copy your API key from https://app.redoc.ly/profile and paste it below:


  Logging in...
Authorization failed. Please check if you entered a valid token.
```

**Logs**
n/a

**`openapi-cli` Version(s)**
1.0.0-beta.32

**`Node.js` Version(s)**
v12.18.2

**Additional context**
- Maybe I would expect to see the stacktrace if we had a `--verbose` type of flag argument.

**Comment by jacobator** [comment]
turned off by default, added --verbose option to login command
