### ISSUE TITLE
Unacceptable kind of an object to dump [object Undefined]

### ISSUE THREAD

**Issue by Foorack** [Redocly/openapi-cli#341]
**Describe the bug**
When trying to generate a bundle it crashes for unknown reason. The bug itself is rather than the error message is very unhelpful.

**To Reproduce**
1. git clone https://github.com/foorack/specification
2. git checkout playermoderations
3. npx @redocly/openapi-cli bundle openapi/openapi.yaml

**Expected behavior**
For it to bundle correctly.

**Logs**
```
$ npx @redocly/openapi-cli bundle openapi/openapi.yaml
npx: installed 87 in 4.085s
bundling openapi/openapi.yaml...
Something went wrong when processing openapi/openapi.yaml:

  - unacceptable kind of an object to dump [object Undefined].

(node:18268) UnhandledPromiseRejectionWarning: YAMLException: unacceptable kind of an object to dump [object Undefined]
    at writeNode (C:\Users\maxfa\AppData\Roaming\npm-cache\_npx\18268\node_modules\@redocly\openapi-cli\node_modules\js-yaml\lib\js-yaml\dumper.js:779:13)
    at writeBlockSequence (C:\Users\maxfa\AppData\Roaming\npm-cache\_npx\18268\node_modules\@redocly\openapi-cli\node_modules\js-yaml\lib\js-yaml\dumper.js:542:9)
    at writeNode (C:\Users\maxfa\AppData\Roaming\npm-cache\_npx\18268\node_modules\@redocly\openapi-cli\node_modules\js-yaml\lib\js-yaml\dumper.js:763:9)
    at writeBlockMapping (C:\Users\maxfa\AppData\Roaming\npm-cache\_npx\18268\node_modules\@redocly\openapi-cli\node_modules\js-yaml\lib\js-yaml\dumper.js:657:10)
    at writeNode (C:\Users\maxfa\AppData\Roaming\npm-cache\_npx\18268\node_modules\@redocly\openapi-cli\node_modules\js-yaml\lib\js-yaml\dumper.js:750:9)
    at writeBlockMapping (C:\Users\maxfa\AppData\Roaming\npm-cache\_npx\18268\node_modules\@redocly\openapi-cli\node_modules\js-yaml\lib\js-yaml\dumper.js:657:10)
    at writeNode (C:\Users\maxfa\AppData\Roaming\npm-cache\_npx\18268\node_modules\@redocly\openapi-cli\node_modules\js-yaml\lib\js-yaml\dumper.js:750:9)
    at writeBlockMapping (C:\Users\maxfa\AppData\Roaming\npm-cache\_npx\18268\node_modules\@redocly\openapi-cli\node_modules\js-yaml\lib\js-yaml\dumper.js:657:10)
    at writeNode (C:\Users\maxfa\AppData\Roaming\npm-cache\_npx\18268\node_modules\@redocly\openapi-cli\node_modules\js-yaml\lib\js-yaml\dumper.js:750:9)
    at writeBlockMapping (C:\Users\maxfa\AppData\Roaming\npm-cache\_npx\18268\node_modules\@redocly\openapi-cli\node_modules\js-yaml\lib\js-yaml\dumper.js:657:10)
(node:18268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**OpenAPI definition**
Git with branch attached.

**`openapi-cli` Version(s)**
1.0.0-beta.54

**`Node.js` Version(s)**
12.16.1

**Comment by Foorack** [comment]
YAML checker also says it is valid YAML...

**Comment by Foorack** [comment]
Actually, this seems to be a problem with a custom plugin. Sorry, closing.
