### ISSUE TITLE
Unable to remove query parameters in visitor

### ISSUE THREAD

**Issue by sirianni** [Redocly/openapi-cli#376]
**Describe the bug**
Unable to remove query parameters in visitor.

**To Reproduce**
Attempted to remove query parameters using a visitor.
```javascript
    'remove-hidden-parameters': () => {
      return {
        Parameter: {
          leave(parameter, ctx) {
            if (parameter['x-hidden']) {
              delete ctx.parent[ctx.key];
            }
          }
        }
      }
```
**Expected behavior**
Expected query parameters with `x-hidden: true` to be removed.

**Actual behavior**
```

YAMLException: unacceptable kind of an object to dump [object Undefined]
    at writeNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/js-yaml/lib/js-yaml/dumper.js:779:13)
    at writeBlockSequence (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/js-yaml/lib/js-yaml/dumper.js:542:9)
    at writeNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/js-yaml/lib/js-yaml/dumper.js:763:9)
    at writeBlockMapping (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
    at writeNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
    at writeBlockMapping (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
    at writeNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
    at writeBlockMapping (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
    at writeNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
    at writeBlockMapping (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10) {
  reason: 'unacceptable kind of an object to dump [object Undefined]',
  mark: undefined
}
```

**`openapi-cli` Version(s)**
What version of `openapi-cli` are you using? 
`1.0.0-beta.18`

**`Node.js` Version(s)**
v14.14.0

**Comment by adamaltman** [comment]
Side note: @sirianni you may want to update to a newer version of `openapi-cli` (we have released 1.0.0-beta.60 which has many improvements and bug fixes since beta.18). https://redoc.ly/docs/cli/changelog/

**Comment by adamaltman** [comment]
Also, this may be helpful: https://redoc.ly/docs/cli/guides/hide-apis/#pluginsdecoratorsremove-internal-schema-properties.js

**Comment by sirianni** [comment]
Thanks @adamaltman .  We are already successfully using the approach from https://redoc.ly/docs/cli/guides/hide-apis/#pluginsdecoratorsremove-internal-schema-properties.js

The issue is that this doesn't work for internal-only query parameters.

**Comment by slavikbez** [comment]
@adamaltman yes
