### ISSUE TITLE
Tool crashing with empty server URL

### ISSUE THREAD

**Issue by gk-hpe** [Redocly/openapi-cli#562]
**Describe the bug**
If the server URL is empty in the OAS, the tool will crash.

**To Reproduce**
1. Given this `.redocly.yaml` file:

    ```yaml
    lint:
      extends:
        - recommended # This is the default (and built in) configuration.
    ```
2. Give below **OpenAPI definition** as input file:

2. Run this command: `openapi lint {oas-filename.yaml}`

**Expected behavior**

I think We need to provide a null check in the [no-undefined-server-variable](https://github.com/Redocly/openapi-cli/blob/master/packages/core/src/rules/oas3/no-undefined-server-variable.ts#L6) rule to prevent crashing.

Also, I think it's a good idea to include a server URL validation, as in the swagger online editor. 

![image](https://user-images.githubusercontent.com/86403210/154891016-d0225309-2f08-4093-a3dd-3053ca7057e5.png)

**Logs**
```js
  - Cannot read property 'match' of null.

/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/rules/oas3/no-undefined-server-variable.js:8
            const urlVariables = ((_a = server.url.match(/{[^}]+}/g)) === null || _a === void 0 ? void 0 : _a.map((e) => e.slice(1, e.length - 1))) || [];
                                                   ^

TypeError: Cannot read property 'match' of null
    at Server (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/rules/oas3/no-undefined-server-variable.js:8:52)
    at visitWithContext (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:205:13)
    at walkNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:104:62)
    at walkNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:119:29)
    at walkNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:154:25)
    at Object.walkDocument (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:32:5)
    at /usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/lint.js:64:16
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/lint.js:5:58)
```

**OpenAPI definition**
```yaml
openapi: 3.0.0
info:
    title: Petstore API
    version: 1.0.0
    description: description

servers:
    - url:
      description: Dev Environment.
```

**`openapi-cli` Version(s)**
1.0.0-beta.69

**`Node.js` Version(s)**
v16.6.1

**Comment by RomanHotsiy** [comment]
It should be resolved by https://github.com/Redocly/openapi-cli/pull/310 but looks there is still some issue.

But just in case, could you try the latest version, you are on beta.69 which is pretty old.

**Comment by gk-hpe** [comment]
I also tried using [1.0.0-beta.82](https://github.com/Redocly/openapi-cli/releases/tag/v1.0.0-beta.82), it seems to have the same problem there too.

**Comment by Marshevskyy** [comment]
Hi @gk-hpe. when you get a chance, could you check the fix on https://github.com/Redocly/openapi-cli/releases/tag/v1.0.0-beta.84?
