### ISSUE TITLE
Tool crashing with invalid enum value

### ISSUE THREAD

**Issue by gk-hpe** [Redocly/openapi-cli#563]
**Describe the bug**
If we provide any values other than an array in the enum, the tool will crash.

**To Reproduce**
1. Given this `.redocly.yaml` file:
   ```yaml
     lint:
       extends:
          - recommended # This is the default (and built in) configuration.
    ```

2. Give below open API definition as an input file.
3. Run this command: `openapi lint {oas-filename.yaml}`.

**Expected behavior**

I think we need to verify that the [enum is an array](https://github.com/Redocly/openapi-cli/blob/v1.0.0-beta.69/packages/core/src/rules/common/no-enum-type-mismatch.ts#L11) before going to filter.

Also, can we provide an array validation for enum similar to the online swagger editor?

![image](https://user-images.githubusercontent.com/86403210/154899864-fd3e13a0-e1a1-441b-b8f9-30430811cb0a.png)

**Logs**
```js
  - schema.enum.filter is not a function.

/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/rules/common/no-enum-type-mismatch.js:9
                const typeMismatchedValues = schema.enum.filter((item) => !utils_1.matchesJsonSchemaType(item, schema.type, schema.nullable));
                                                         ^

TypeError: schema.enum.filter is not a function
    at Schema (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/rules/common/no-enum-type-mismatch.js:9:58)
    at visitWithContext (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:205:13)
    at walkNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:104:62)
    at walkNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:154:25)
    at walkNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:154:25)
    at walkNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:154:25)
    at walkNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:154:25)
    at walkNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:154:25)
    at walkNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:154:25)
    at walkNode (/usr/local/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/walk.js:154:25)
```
**OpenAPI definition**
```yaml
openapi: 3.0.0
info:
  title: Petstore API
  version: 1.0.0
  description: description

paths:

  /v1/pets/{petId}:
    get:
      operationId: getPet
      parameters:
      - name: petId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Details of the requested pet.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

        '400':
          description: Bad Request.
        '500': 
          description: Internal Server Error.

components:

  schemas:
    Pet:
      type: object
      required:
        -  id
      properties:
        name:
          type: string
        id:
          type: string
          format: uuid
        status:
          type: string
          enum: string
````

**`openapi-cli` Version(s)**
1.0.0-beta.69

**`Node.js` Version(s)**
v16.6.1

**Comment by RomanHotsiy** [comment]
It should be resolved by https://github.com/Redocly/openapi-cli/pull/310 but looks there is still some issue.

But just in case, could you try the latest version, you are on beta.69 which is pretty old.

**Comment by gk-hpe** [comment]
I also tried using  [1.0.0-beta.82](https://github.com/Redocly/openapi-cli/releases/tag/v1.0.0-beta.82), it seems to have the same problem there too.

**Comment by adamaltman** [comment]
It isn't resolved by #310 because that handles null, but it doesn't handle other types like a string in this case (enum expects an array).

**Comment by Marshevskyy** [comment]
Hi @gk-hpe. when you get a chance, could you check the fix on https://github.com/Redocly/openapi-cli/releases/tag/v1.0.0-beta.84?

**Comment by gk-hpe** [comment]
@Marshevskyy Thanks, It works well now.
