### ISSUE TITLE
Handle errors during the YAML parsing / file read operations 

### ISSUE THREAD

**Issue by knidarkness** [Redocly/openapi-cli#69]
Handle errors during the YAML parsing/file read operations. Related PR #68 which introduced a problem with FIXMEs.

**Comment by adamaltman** [comment]
I received the same/similar issue.  It shows me the line and column, but not the file:

```
➜  RebillyAPI git:(master) ✗ yarn test
yarn run v1.19.2
$ openapi validate

/Users/adam/Projects/Rebilly/RebillyAPI/node_modules/js-yaml/lib/js-yaml/loader.js:173
  throw generateError(state, message);
  ^
YAMLException: bad indentation of a mapping entry at line 2, column 13:
      properties:
                ^
    at generateError (/Users/adam/Projects/Rebilly/RebillyAPI/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/Users/adam/Projects/Rebilly/RebillyAPI/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/Users/adam/Projects/Rebilly/RebillyAPI/node_modules/js-yaml/lib/js-yaml/loader.js:1107:7)
    at composeNode (/Users/adam/Projects/Rebilly/RebillyAPI/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/Users/adam/Projects/Rebilly/RebillyAPI/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/Users/adam/Projects/Rebilly/RebillyAPI/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at load (/Users/adam/Projects/Rebilly/RebillyAPI/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at Object.safeLoad (/Users/adam/Projects/Rebilly/RebillyAPI/node_modules/js-yaml/lib/js-yaml/loader.js:1618:10)
    at resolve (/Users/adam/Projects/Rebilly/RebillyAPI/node_modules/@redocly/openapi-cli/dist/resolver.js:85:34)
    at resolveNode (/Users/adam/Projects/Rebilly/RebillyAPI/node_modules/@redocly/openapi-cli/dist/resolver.js:201:22) {
  name: 'YAMLException',
  reason: 'bad indentation of a mapping entry',
```
